# Generated by Django 4.2.1 on 2023-05-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_image',
        ),
    ]
